name: Release Docker Multi-arch Image CI & CD

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Running Compile Next Multi-arch Docker Release Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PicImpact
        uses: actions/checkout@v4
      - name: Get Version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: set_up_buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push version
        id: docker_build_version
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/picimpact:${{ steps.get_version.outputs.VERSION }}
